In [2]:
!pip install tensorflow-text

     |████████████████████████████████| 4.9 MB 5.1 MB/s 
     |████████████████████████████████| 462 kB 52.8 MB/s 


In [3]:
import tensorflow_hub as hub
import tensorflow_text as text

In [4]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [5]:
bert_preprocess_model = hub.KerasLayer(preprocess_url) # creating hub layer

`bert_preprocess_model` is a function pointer. Will be performing pre-processing in our raw text. This pre-processing will be accepted by the **BERT** model. 

In [28]:
text_test = ['This is a notebook','This is BERT model'] # sample text
text_preprocessed = bert_preprocess_model(text_test) # dictionary
text_preprocessed.keys() # the keys in dictionary

dict_keys(['input_word_ids', 'input_type_ids', 'input_mask'])

In [29]:
len(text_test[0].split())

4

In [30]:
text_preprocessed['input_word_ids'] # The first sentence has 4 words but this vector has marked 6 words 

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  2023,  2003,  1037, 14960,   102,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

AS BERT WILL PUT SPACIAL TOKEN CALLED **CLS** IN THE BEGINNING AND **SEP** AT THE END TO SEPERATE TWO SENTENCES.

'CLS This is a notebook SEP'

'CLS This is BERT model SEP'

text_preprocessed['input_type_ids']

In [32]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [34]:
bert_model = hub.KerasLayer(encoder_url) # function pointer to the model

In [36]:
bert_results = bert_model(text_preprocessed) # supplying pre-processed text
bert_results.keys()

dict_keys(['encoder_outputs', 'default', 'pooled_output', 'sequence_output'])

`pooled_output` is embedding for entire sentences. 768 size vector accuratly represents a sentence.

In [38]:
bert_results['pooled_output'] # sentence embedding vector can be used in NLP task directly.

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.85602754, -0.21811046,  0.44990915, ...,  0.40079123,
        -0.5726854 ,  0.8601298 ],
       [-0.87443405, -0.29097676,  0.0370084 , ..., -0.1664732 ,
        -0.56644905,  0.8661555 ]], dtype=float32)>

In [39]:
# individual word embedding vector
bert_results['sequence_output'] # for each word of each sentence it will have 768 size vector

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-0.06484351,  0.18709818, -0.08521189, ..., -0.22052334,
          0.123952  ,  0.3336754 ],
        [-0.5515665 , -0.17585446,  0.5669601 , ..., -0.84280074,
          0.5317802 ,  0.37333864],
        [ 0.03778867, -0.2596987 ,  0.5838067 , ..., -0.0258976 ,
          0.47649878,  1.2347623 ],
        ...,
        [-0.03841615,  0.04802167,  0.2363291 , ..., -0.03014144,
          0.1888106 ,  0.4226545 ],
        [-0.01032433,  0.07828996,  0.27397788, ...,  0.04016506,
          0.13728039,  0.3544454 ],
        [-0.19565459,  0.00866852,  0.28279334, ...,  0.11817306,
          0.07485361,  0.32298705]],

       [[-0.2806494 ,  0.166391  ,  0.26657495, ..., -0.36268088,
          0.12614633,  0.4466243 ],
        [-0.6941366 , -0.22901328,  0.45368475, ..., -0.5584245 ,
          0.64315647,  0.30351117],
        [-0.41080892, -0.5306831 ,  0.6855127 , ..., -0.25293842,
          0.32183754,  0.86481696],
        ...,

We have two sentences and for each individual sentence we will have some padding and total 128 length.

CLS 423 54 435 545 343 SPE 0 0 0 0 -> 128

and we will have 768 size vector for each word(128) in a sentence

In [43]:
# small bert based has 12 encoders
len(bert_results['encoder_outputs'])

12

In [45]:
bert_results['encoder_outputs'][0] # output of first encoder

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.17943142, -0.02459913, -0.11352944, ...,  0.07549001,
          0.02028152,  0.11161339],
        [-0.42330408,  0.18787727,  0.04687632, ...,  0.15582815,
          0.5990445 ,  0.11757566],
        [-1.0326885 , -0.61222714, -0.5654511 , ...,  0.34777492,
          0.50954247,  0.6409524 ],
        ...,
        [-0.12242051, -0.41352063,  0.54070365, ...,  0.2826595 ,
         -0.25184885,  0.15229562],
        [-0.21878125, -0.41811937,  0.4171768 , ...,  0.30987322,
         -0.14763938,  0.0935528 ],
        [-0.08114739, -0.36670592,  0.45129043, ...,  0.6468837 ,
         -0.47372878,  0.03105961]],

       [[ 0.17464432,  0.04171177,  0.00219975, ...,  0.11144857,
          0.05800582,  0.05139124],
        [-0.4036029 ,  0.49570137,  0.03233614, ...,  0.25487685,
          0.5273421 , -0.1384246 ],
        [-0.55064833, -0.12166771, -0.4984468 , ...,  0.36268017,
          0.33495247,  0.3313707 ],
        ...,

In [46]:
bert_results['encoder_outputs'][-1] # output of last encoder

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-0.06484351,  0.18709818, -0.08521189, ..., -0.22052334,
          0.123952  ,  0.3336754 ],
        [-0.5515665 , -0.17585446,  0.5669601 , ..., -0.84280074,
          0.5317802 ,  0.37333864],
        [ 0.03778867, -0.2596987 ,  0.5838067 , ..., -0.0258976 ,
          0.47649878,  1.2347623 ],
        ...,
        [-0.03841615,  0.04802167,  0.2363291 , ..., -0.03014144,
          0.1888106 ,  0.4226545 ],
        [-0.01032433,  0.07828996,  0.27397788, ...,  0.04016506,
          0.13728039,  0.3544454 ],
        [-0.19565459,  0.00866852,  0.28279334, ...,  0.11817306,
          0.07485361,  0.32298705]],

       [[-0.2806494 ,  0.166391  ,  0.26657495, ..., -0.36268088,
          0.12614633,  0.4466243 ],
        [-0.6941366 , -0.22901328,  0.45368475, ..., -0.5584245 ,
          0.64315647,  0.30351117],
        [-0.41080892, -0.5306831 ,  0.6855127 , ..., -0.25293842,
          0.32183754,  0.86481696],
        ...,

In [47]:
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>

Output of last `encoder_outputs` will be equal to `sequence_output`